import { jsPDF } from 'jspdf';
import type { Message } from '@/types/chat';

function getMessageText(msg: Message): string {
  if (!msg.parts || !msg.parts.length) return '';
  return msg.parts
    .map((p) => p.text || '')
    .filter(Boolean)
    .join('\n');
}

export async function downloadChatPDF(messages: Message[]): Promise<void> {
  if (!messages.length) {
    throw new Error('No messages to download');
  }

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;
  const contentWidth = pageWidth - margin * 2;

  let y = 20;

  // Header bar
  doc.setFillColor(220, 38, 38);
  doc.rect(0, 0, pageWidth, 18, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Red Whale V1 — Chat Export', margin, 12);

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text(new Date().toLocaleString(), pageWidth - margin, 12, { align: 'right' });

  y = 28;

  // Messages
  for (const msg of messages) {
    const isUser = msg.role === 'user';
    const label = isUser ? 'You' : 'Red Whale AI';
    const labelColor: [number, number, number] = isUser ? [220, 38, 38] : [37, 99, 235];
    const text = getMessageText(msg);
    if (!text.trim()) continue;

    // Label bubble
    doc.setFillColor(...labelColor);
    doc.roundedRect(margin, y - 4, label === 'You' ? 14 : 32, 7, 2, 2, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.text(label, margin + 2, y + 0.5);

    y += 10;

    // Message text
    doc.setTextColor(30, 30, 30);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);

    const lines = doc.splitTextToSize(text, contentWidth);

    for (const line of lines) {
      if (y > pageHeight - margin) {
        doc.addPage();
        y = margin;
      }
      doc.text(line, margin, y);
      y += 4.5;
    }

    y += 6;

    if (y > pageHeight - 40 && messages.indexOf(msg) < messages.length - 1) {
      doc.addPage();
      y = margin;
    }
  }

  // Footer
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setTextColor(150, 150, 150);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.text(
      `Red Whale V1  |  Page ${i} of ${totalPages}  |  Generated by Red Whale AI`,
      pageWidth / 2,
      pageHeight - 6,
      { align: 'center' }
    );
  }

  doc.save(`RedWhale_Chat_${new Date().toISOString().slice(0, 10)}.pdf`);
}
